[tool]
    [tool.setuptools]
    # The repository contains no python modules
    py-modules = []

    [tool.ruff]
    extend-exclude                 = []
    format.docstring-code-format   = true
    format.quote-style             = "single"
    line-length                    = 160
    lint.exclude                   = ["tests/**/*"]
    lint.isort.force-single-line   = true
    lint.isort.lines-between-types = 1
    lint.select                    = ["B", "C4", "C901", "E", "F", "I", "N", "PL", "S", "UP", "W"]
    exclude = [
        "test_eth_phy.py",
    ]

    [tool.codespell]
    skip = "build,*.drawio"
    ignore-words-list = "emac"
    write-changes = true
