# Build test rules for common examples
# This file is used by idf-build-apps to determine which examples to build and test

common_examples/iperf:
  disable:
    - if: IDF_VERSION < "5.5.1"
      temporary: true
      reason: IDF-14291
  enable:
    - if: IDF_TARGET in ["esp32", "esp32p4"]
      temporary: true
      reason: to save build time, build for Extensa and RISC-V

common_examples/simple-ethernet:
  disable:
    - if: IDF_VERSION < "5.5.1"
      temporary: true
      reason: IDF-14291
  enable:
    - if: IDF_TARGET in ["esp32", "esp32p4"]
      temporary: true
      reason: to save build time, build for Extensa and RISC-V

common_examples/tcp_server:
  disable:
    - if: IDF_VERSION < "5.5.1"
      temporary: true
      reason: IDF-14291
  enable:
    - if: IDF_TARGET in ["esp32", "esp32p4"]
      temporary: true
      reason: to save build time, build for Extensa and RISC-V

common_examples/tcp_client:
  disable:
    - if: IDF_VERSION < "5.5.1"
      temporary: true
      reason: IDF-14291
  enable:
    - if: IDF_TARGET in ["esp32", "esp32p4"]
      temporary: true
      reason: to save build time, build for Extensa and RISC-V
