# Build test rules for PHY tester
# This file is used by idf-build-apps to determine which examples to build and test

phy_tester:
  disable:
    - if: IDF_VERSION < "5.5.1"
      temporary: true
      reason: IDF-14291
  enable:
    - if: IDF_TARGET in ["esp32", "esp32p4"]
