name: Build KSZ8863 Examples

on:
  push:
    branches:
      - "!refs/pull/*" # Exclude push events related to PRs
  pull_request:

jobs:
  build:
    strategy:
      fail-fast: false
      matrix:
        idf_ver: ["release-v5.3", "release-v5.4", "release-v5.5", "latest"]
        example: ["ksz8863/examples/simple_switch",
                  "ksz8863/examples/switch_mode",
                  "ksz8863/examples/two_ports_mode",
                  ]
        idf_target: ["esp32"]

    runs-on: ubuntu-24.04
    container: espressif/idf:${{ matrix.idf_ver }}
    steps:
      - name: Checkout esp_eth_drivers
        uses: actions/checkout@master
        with:
          path: esp_eth_drivers
      - name: Build ${{ matrix.example }} with IDF-${{ matrix.idf_ver }} for ${{ matrix.idf_target }}
        env:
          IDF_TARGET: ${{ matrix.idf_target }}
        shell: bash
        run: |
          . ${IDF_PATH}/export.sh
          pip install idf-build-apps
          cd $GITHUB_WORKSPACE/esp_eth_drivers/${{ matrix.example }}
          idf-build-apps build -p . --target ${{ matrix.idf_target }} --build-dir build_@t_@w --check-warnings
