name: Build All

on:
  pull_request:


jobs:
  build:
    # don't run build when the PR branch is a release-please branch
    if: ${{ !startsWith(github.head_ref, 'release-please') }}
    strategy:
      fail-fast: false
      matrix:
        idf_ver: ["release-v5.4", "release-v5.5", "latest"]

    runs-on: ubuntu-24.04
    container: espressif/idf:${{ matrix.idf_ver }}
    steps:
      - uses: actions/checkout@v4
      - name: Install Dependencies
        shell: bash
        run: |
          . ${IDF_PATH}/export.sh
          pip install -U idf-ci
      - name: Build ESP-IDF Projects
        id: build-esp-idf-projects
        shell: bash
        run: |
          . ${IDF_PATH}/export.sh
          idf-ci build run
      - name: Upload Artifact
        if: success() || (failure() && steps.build-esp-idf-projects.outcome == 'failure')
        uses: actions/upload-artifact@v4
        with:
          name: build-artifacts-${{ matrix.idf_ver }}
          path: |
            **/build_*_*/build.log
            **/build*/size.json
            **/build*/project_description.json
            app_info_*.txt
            build_summary_*.xml
            size_info_*.txt
          retention-days: 5
