# FILE: .github/workflows/pr_approved.yml

name: Sync approved PRs to internal codebase
on:
  pull_request_target:
    types: [labeled]

jobs:
  sync_prs_to_internal_codebase:
    name: Sync approved PRs to internal codebase
    env:
      GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      GITLAB_URL: ${{ secrets.GITLAB_URL }}
      GITLAB_TOKEN: ${{ secrets.GITLAB_TOKEN }}
      GIT_CONFIG_NAME: ${{ secrets.GIT_CONFIG_NAME }}
      GIT_CONFIG_EMAIL: ${{ secrets.GIT_CONFIG_EMAIL }}
      JIRA_PROJECT: IDFGH
    runs-on: ubuntu-latest
    if: (github.event.label.name == 'PR-Sync-Merge')   ||
        (github.event.label.name == 'PR-Sync-Rebase')  ||
        (github.event.label.name == 'PR-Sync-Update')
    steps:
      - uses: actions/checkout@v4

      - name: Sync approved PRs to internal codebase
        uses: espressif/sync-pr-to-gitlab@v1
