---
# FILE: .github/workflows/sync-jira.yml

# This GitHub Actions workflow synchronizes GitHub issues, comments, and pull requests with Jira.
# It triggers on new issues, issue comments, and on pull requests.
# The workflow uses a custom action to perform the synchronization with Jira (espressif/sync-jira-actions).

name: 🔷 Sync to Jira

run-name: >
  Sync to Jira -
  ${{ github.event_name == 'issue_comment' && 'Issue Comment' ||
      github.event_name == 'pull_request' && 'Pull Requests' ||
      github.event_name == 'issues' && 'New Issue' ||
      github.event_name == 'workflow_dispatch' && 'Manual Sync' }}

on:
  issues: {types: [opened]}
  issue_comment: {types: [created, edited, deleted]}
  pull_request: {types: [opened, reopened, closed]}
  workflow_dispatch:
    inputs:
      action: {description: 'Action to be performed', required: true, default: 'mirror-issues'}
      issue-numbers: {description: 'Issue numbers to sync (comma-separated)', required: true}

jobs:
  sync-to-jira:
    name: >
      Sync to Jira
    # Don't run for release pull requests
    if: ${{ !(github.event_name == 'pull_request' && startsWith(github.head_ref, 'release-please-')) }}
    runs-on: ubuntu-latest
    permissions:
      contents: read
      issues: write
      pull-requests: write
    steps:
        # When PR is commented, event is handled as `issue_comment` and there are no details about PR.
        # Hence get more info by script and stop the process if it's release PR.
      - name: Stop for release-please PR comments
        if: ${{ github.event_name == 'issue_comment' && github.event.issue.pull_request }}
        uses: actions/github-script@v7
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          script: |
            const prNumber = context.payload.issue.number
            const pr = await github.rest.pulls.get({
              ...context.repo,
              pull_number: prNumber,
            })
            const headRef = pr.data.head.ref || ''
            core.info(`PR #${prNumber} head ref: ${headRef}`)
            if (headRef.startsWith('release-please')) {
              core.warning('release-please PR comment detected; stopping workflow early.')
              core.setOutput('skip', 'true')
            }
        id: guard

      - name: Check out
        if: ${{ steps.guard.outputs.skip == 'false' }}
        uses: actions/checkout@v4

      - name: Run synchronization to Jira
        if: ${{ steps.guard.outputs.skip == 'false' }}
        uses: espressif/sync-jira-actions@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          JIRA_PASS: ${{ secrets.JIRA_PASS }}
          JIRA_PROJECT: IDFGH
          JIRA_COMPONENT: ethernet
          JIRA_URL: ${{ secrets.JIRA_URL }}
          JIRA_USER: ${{ secrets.JIRA_USER }}
